# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import (QCoreApplication, QDate, QDataStream, QMetaObject,)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont )
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QLabel, QLineEdit, QPushButton, QVBoxLayout


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(269, 385)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(269, 385))
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtResult = QtWidgets.QLineEdit(self.centralwidget)
        self.txtResult.setMinimumSize(QtCore.QSize(0, 41))
        self.txtResult.setMaximumSize(QtCore.QSize(251, 41))
        font = QtGui.QFont()
        font.setFamily("Muli SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txtResult.setFont(font)
        self.txtResult.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtResult.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtResult.setObjectName("txtResult")
        self.verticalLayout.addWidget(self.txtResult)
        self.gb_angka = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_angka.setMinimumSize(QtCore.QSize(251, 279))
        self.gb_angka.setMaximumSize(QtCore.QSize(251, 279))
        self.gb_angka.setObjectName("gb_angka")
        self.btn1 = QtWidgets.QPushButton(self.gb_angka)
        self.btn1.setGeometry(QtCore.QRect(10, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn1.setText("1")
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.gb_angka)
        self.btn2.setGeometry(QtCore.QRect(70, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn2.setText("2")
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.gb_angka)
        self.btn3.setGeometry(QtCore.QRect(130, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn3.setText("3")
        self.btn3.setObjectName("btn3")
        self.btnMin = QtWidgets.QPushButton(self.gb_angka)
        self.btnMin.setGeometry(QtCore.QRect(190, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnMin.setFont(font)
        self.btnMin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnMin.setText("-")
        self.btnMin.setObjectName("btnMin")
        self.btn6 = QtWidgets.QPushButton(self.gb_angka)
        self.btn6.setGeometry(QtCore.QRect(130, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn6.setText("6")
        self.btn6.setObjectName("btn6")
        self.btnDivide = QtWidgets.QPushButton(self.gb_angka)
        self.btnDivide.setGeometry(QtCore.QRect(190, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnDivide.setFont(font)
        self.btnDivide.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnDivide.setText("/")
        self.btnDivide.setObjectName("btnDivide")
        self.btn4 = QtWidgets.QPushButton(self.gb_angka)
        self.btn4.setGeometry(QtCore.QRect(10, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn4.setText("4")
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.gb_angka)
        self.btn5.setGeometry(QtCore.QRect(70, 80, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn5.setText("5")
        self.btn5.setObjectName("btn5")
        self.btn9 = QtWidgets.QPushButton(self.gb_angka)
        self.btn9.setGeometry(QtCore.QRect(130, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn9.setText("9")
        self.btn9.setObjectName("btn9")
        self.btn7 = QtWidgets.QPushButton(self.gb_angka)
        self.btn7.setGeometry(QtCore.QRect(10, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn7.setText("7")
        self.btn7.setObjectName("btn7")
        self.btnPlus = QtWidgets.QPushButton(self.gb_angka)
        self.btnPlus.setGeometry(QtCore.QRect(190, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPlus.setFont(font)
        self.btnPlus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnPlus.setText("+")
        self.btnPlus.setObjectName("btnPlus")
        self.btn8 = QtWidgets.QPushButton(self.gb_angka)
        self.btn8.setGeometry(QtCore.QRect(70, 140, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn8.setText("8")
        self.btn8.setObjectName("btn8")
        self.btnClear = QtWidgets.QPushButton(self.gb_angka)
        self.btnClear.setGeometry(QtCore.QRect(10, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnClear.setFont(font)
        self.btnClear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnClear.setText("c")
        self.btnClear.setObjectName("btnClear")
        self.btn0 = QtWidgets.QPushButton(self.gb_angka)
        self.btn0.setGeometry(QtCore.QRect(70, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn0.setText("0")
        self.btn0.setObjectName("btn0")
        self.btnKali = QtWidgets.QPushButton(self.gb_angka)
        self.btnKali.setGeometry(QtCore.QRect(130, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnKali.setFont(font)
        self.btnKali.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnKali.setText("*")
        self.btnKali.setObjectName("btnKali")
        self.btnHasil = QtWidgets.QPushButton(self.gb_angka)
        self.btnHasil.setGeometry(QtCore.QRect(190, 200, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnHasil.setFont(font)
        self.btnHasil.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnHasil.setText("=")
        self.btnHasil.setObjectName("btnHasil")
        self.verticalLayout.addWidget(self.gb_angka)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 269, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menufile.addAction(self.actionQuit)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Calculator"))
        self.gb_angka.setTitle(_translate("MainWindow", "Kalkulator"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
    
class Calculator(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(Calculator, self).__init__()

        self.setupUi(self)

        self.result = "0"
        self.operator = ""

        #Quit Menu Option
        self.actionQuit.triggered.connect(self.close)

        # Button Presses
        self.btn0.clicked.connect(self.nolPressed)
        self.btn1.clicked.connect(self.satuPressed)
        self.btn2.clicked.connect(self.duaPressed)
        self.btn3.clicked.connect(self.tigaPressed)
        self.btn4.clicked.connect(self.empatPressed)
        self.btn5.clicked.connect(self.limaPressed)
        self.btn6.clicked.connect(self.enamPressed)
        self.btn7.clicked.connect(self.tujuhPressed)
        self.btn8.clicked.connect(self.delapanPressed)
        self.btn9.clicked.connect(self.sembilanPressed)

        #clear Button
        self.btnClear.clicked.connect(self.clear)

        #Operation Button
        self.btnPlus.clicked.connect(self.plus)
        self.btnMin.clicked.connect(self.minus)
        self.btnDivide.clicked.connect(self.bagi)
        self.btnKali.clicked.connect(self.kali)

        #Hasil Button
        self.btnHasil.clicked.connect(self.calculate)


    def nolPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}0")
        else:
            self.txtResult.setText("0")
    
    def satuPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}1")
        else:
            self.txtResult.setText("1")
    
    def duaPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}2")
        else:
            self.txtResult.setText("2")

    def tigaPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}3")
        else:
            self.txtResult.setText("3")

    def empatPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}4")
        else:
            self.txtResult.setText("4")

    def limaPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}5")
        else:
            self.txtResult.setText("5")

    def enamPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}6")
        else:
            self.txtResult.setText("6")

    def tujuhPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}7")
        else:
            self.txtResult.setText("7")

    def delapanPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}8")
        else:
            self.txtResult.setText("8")
    
    def sembilanPressed(self):
        val = self.txtResult.text()
        if not val == "0":
            self.txtResult.setText(f"{val}9")
        else:
            self.txtResult.setText("9")
    
    def clear(self):
        self.txtResult.setText("0")

    def plus(self):
        val = self.txtResult.text()
        self.txtResult.setText(f"{val} + ")

    def minus(self):
        val = self.txtResult.text()
        self.txtResult.setText(f"{val} - ")

    def bagi(self):
        val = self.txtResult.text()
        self.txtResult.setText(f"{val} / ")

    def kali(self):
        val = self.txtResult.text()
        self.txtResult.setText(f"{val} * ")

    def calculate(self):
        expression = self.txtResult.text()
        try:
            result = eval(expression)
            self.txtResult.setText(str(result))
        except Exception as e:
            self.txtResult.setText("Error")

    def clear(self):
        self.txtResult.setText("0")


if __name__== '__main__':
    import sys
    app = QApplication(sys.argv)

    calc = Calculator()
    calc.show()

    sys.exit(app.exec_())

